title: Mike Levin on Linux, Python, vim & git (LPvg)
author: Mike Levin
base_url: https://mikelev.in/
permalink: /:slug/
gaid: G-RX2D1N1P2Y
apex: MikeLev.in

# Conversion
markdown: GFM
highlighter: rouge

kramdown:
  syntax_highlighter: rouge
  input: GFM

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
      author: "Mike Levin"
