title: Mike Levin on Linux, Python, vim & git (LPvg)
author: Mike Levin
base_url: https://mikelev.in/
permalink: /:slug/
gaid: G-RX2D1N1P2Y
apex: MikeLev.in

# Conversion
markdown:    kramdown
highlighter: rouge

# Markdown Processors
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
      author: "Mike Levin"

