title: Mike Levin SEO
author: Mike Levin, SEO in NYC
apex: MikeLev.in
permalink: /:slug/
gaid: G-RX2D1N1P2Y

# Conversion
markdown:    kramdown
highlighter: rouge

# Markdown Processors
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
      author: "Mike Levin"

# Metadata
category_filter:
  - article
  - blog
  - blog post
  - book
  - browser
  - category
  - challenge
  - chrome
  - cloud
  - code
  - command
  - commit
  - content
  - control
  - data
  - default
  - description
  - device
  - dictionary
  - documentation
  - download
  - easy
  - editing
  - education
  - effect
  - environment
  - error
  - experience
  - explore
  - field
  - file
  - fo
  - folder
  - free
  - frequency
  - function
  - game
  - hardware
  - home
  - idea
  - image
  - index
  - install
  - job
  - journal
  - knowledge
  - label
  - labels
  - language
  - laptop
  - library
  - life
  - link
  - list
  - machine
  - markdown
  - mike levin
  - mikelev.in
  - money
  - na
  - none
  - opportunity
  - package
  - page
  - path
  - playwright
  - possibility
  - post
  - program
  - programming
  - project
  - push
  - release
  - repo
  - repository
  - research
  - result
  - server
  - sharing
  - site
  - slug
  - software
  - strength
  - subsystem
  - system
  - tag
  - task
  - tech
  - technology
  - testing
  - title
  - tool
  - transition
  - update
  - upgrade
  - url
  - user
  - version
  - video
  - website
  - window
  - world
  - writing
  - windows subsystem
  - moz links api
  - graphics
  - edit
  - ufo
  - collaboriation
  - security
  - decision
  - evidence
  - thought
  - cat
  - human
  - edit
  - internet
  - homepage
  - web
  - mapping

